### PR TITLE
feat: add theme preferences to configuration

### PR DESCRIPTION
**Pull request by fraso-dev**
Using `load()` instead of `setup()` to load defaults and simplified config manager to discard initial nil config table.
The idea is that the default config should be already filled when `load()` is called at startup, so the `setup` function can be optionally used to let users change defaults (also updated `README.md` for configuration options).
Also changed some default highlight groups and make them use some config values.

### CODE REVIEW

**Comment by blazkowolf** [comment]
Thanks for your effort on this @fraso-dev. At cursory glance everything looks great, but I'll do a proper review and get this merged this evening.

**Comment by fraso-dev** [comment]
I really like this project (and this colorscheme). 
Looking forward to contribute more in the future.. I'm currently learning a lot and trying to improve my git/versioning skills also.

**Comment by blazkowolf** [comment]
I'm glad you like it, and I appreciate the work you've done!

**Review by blazkowolf — APPROVED** [review]
Everything looks great! I really like the preferences you added to the config - it gives the theme a lot more personality than it had before.

**Pull request merged**
